### PR TITLE
Explicitly set url scheme when passing X-Forwarded-Proto

### PR DESCRIPTION
**Pull request by blaix**
This will let non-secure proxies tell a secure service to construct http URLs instead of https.

### CODE REVIEW

**Comment by thomasw** [comment]
As discussed on our call, we should be able to just toggle the `HTTPS` environ to on or off. Though, what you're doing here may be better because we might be able to eliminate the csrf monkey patch that we have. Maybe we should do both though?

https://github.com/django/django/blob/1.6.9/django/http/request.py#L119-L120

**Comment by blaix** [comment]
I think we should do both.

**Comment by blaix** [comment]
updated

**Comment by thomasw** [comment]
:+1:

**Pull request merged**
