### PR TITLE
Include contrib module in installed package

### PR DESCRIPTION
**Pull request by blaix**
See https://github.com/yola/yolacom/pull/1775#issuecomment-76513787

### CODE REVIEW

**Comment by thomasw** [comment]
:+1:

**Comment by zoidbergwill** [comment]
version bump and changelog entry?

**Comment by zoidbergwill** [comment]
I was gonna retract my statement, but it is on YolaPI. So it should still need the version bump.

**Comment by blaix** [comment]
Yeah, I usually like to do those in a separate pull, but this change is all about the released package, so I'm going to add it to this one. Stand by...

**Comment by blaix** [comment]
Bumped. Can I get a new thumb?

**Comment by adrianmoisey** [comment]
:+1:

**Comment by zoidbergwill** [comment]
Yeah, some people think it should be another pull, and some people think version bumps and changelog changes should happen in master.

Generally our client libraries get one pull of changes per version bump, so I'm not against them going in the same pull. 

I should've commented saying that it's okay if you were gonna do it in another PR or somewhere else.

**Comment by stefanor** [comment]
I don't think we want a global `contrib` package like that. It should probably be inside `proxyprefix`, e.g. `proxyprefix.contrib`.

Otherwise what happens if two libraries ship a `contrib` package?

**Comment by blaix** [comment]
It is `proxyprefix.contrib`...

**Comment by blaix** [comment]
Oops, yeah. My CHANGELOG entry is wrong. I'll fix it.

**Comment by blaix** [comment]
#6

**Comment by stefanor** [comment]
In that case, why did you need to switch to find_packages?

**Comment by thomasw** [comment]
From https://docs.python.org/2/distutils/setupscript.html#listing-whole-packages

> (Keep in mind that although package_dir applies recursively, you must explicitly list all packages in packages: the Distutils will not recursively scan your source tree looking for any directory with an __init__.py file.)

I've read this like 4 times, and I'm still not sure my interpretation is correct. If I understand things correctly `package_dir` can be used in addition to or instead of `packages`? `package_dir` will work recursively but packages does not? I've never tried to use `package_dir`, so I really don't know the answer here. If `package_dir` were used here, would the parameter be `package_dir={'proxyprefix':'proxyprefix'}`? :8ball: 

Justin made this change because `proxyprefix.contrib` was not being included in the dist.

**Comment by stefanor** [comment]
Right, I always forget about that. This is why `find_packages` exists...

**Comment by zoidbergwill** [comment]
I remember going through this confusion with healthcheck too.

**Pull request merged**
