### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by blaix**
The setup.py is kind of sparse. I see conflicting examples in our packages. Please comment if you have any thoughts on what should go in there.

### CODE REVIEW

**Comment by beck** [comment]
Question: Is there any value to having the version defined in init?

I think the module docstring is an inappropriate setup.py description.  Reasons:

1. I like a healthy docstring with (when applicable) sample usage, more often than not, the string will be multi-line.

1. The [setup script docs](https://docs.python.org/2/distutils/setupscript.html#additional-meta-data) say the description should be:
   > A single line of text, not more than 200 characters.

   When looking at Reason 1, makes the docstring inappropriate setup.py description.  It may be appropriate to use as its `long_description`.

I'm leaning Nay for importing the version and description and define both explicitly.

@stefanor and @RayeN usually have opinions on such things that I enjoy disagreeing with until they convince me I'm wrong.

**Comment by blaix** [comment]
The only reason I'm importing version is because that's how I've always seen it done, but I never understood why. Would like to hear from @RayeN or @thomasw on that, because they're the people I usually use for setup.py templates.

I agree with your reasoning for giving setup.py it's own description string. Thanks. Will fix.

**Comment by thomasw** [comment]
I don't have much time to respond to this further, but it is a useful debugging tool to make it so that the version is exposed programmatically. The rationale for importing it from the installable itself is because it reduces version number specification duplication (ideally the version number is only defined in one place, and only has to be changed one time to bump a version). The approach Justin took here is sometimes problematic, but it isn't in this case and it won't be problematic for most simple installables.

Putting the setup.py long description as a docstring in the `__init__.py` file means you can call `help(proxyprefix)` and get just in time documentation when you're using something via the shell. Even if you don't expose that same string via setup.py, it is a best practice to have something useful there.

**Comment by stefanor** [comment]
Having version in `__init__.py` is sometimes useful.

Importing the module in `setup.py` can be problematic if supporting python 2 & 3 via `2to3`, so, having been bitten by that in the past, I tend to avoid it now. But `2to3` is going out of vogue, so, that's probably not a big deal.

Agreed with @beck on the long description being too long for `description`.

If possible, you should support `setup.py test`. It's the standard way to test a python library.

**Comment by blaix** [comment]
Updated to move module doc to `long_description` and support `setup.py test`.

**Comment by blaix** [comment]
Oops, I added it to travis, but haven't configured it yet. Didn't realize it would try to run without the config. I was in the middle of that on my desktop but am on my laptop now. I'll finish the travis setup soon. Until then, please ignore the red x's. The tests are totally passing.

**Comment by thomasw** [comment]
@blaix: your tests are failing.

**Comment by blaix** [comment]
Thanks @thomasw

**Comment by blaix** [comment]
passing!

**Comment by stefanor** [comment]
LICENSE?

**Comment by blaix** [comment]
What do we like to use? MIT?

**Comment by stefanor** [comment]
Yeah. MIT/Expat ("MIT" doesn't accurately specify a single licence, only a style of license).

**Comment by blaix** [comment]
Merged master and added license

**Comment by thomasw** [comment]
You need
https://github.com/yola/property-caching/blob/master/setup.py#L9
(and probably)  https://github.com/yola/property-caching/blob/master/setup.py#L17
and https://github.com/yola/property-caching/blob/master/MANIFEST.in

**Comment by blaix** [comment]
Thanks. Done.

**Comment by blaix** [comment]
Question: the djproxy middleware in `contrib` requires `djproxy >= 2.0.0`. Wondering if I need to put that in `setup.py`, since the services using this won't need the djproxy part...

**Comment by blaix** [comment]
or is that something I should just document in the README?

**Comment by RayeN** [comment]
I don't think we should add it as dependency  `setup.py`, +1 for README

**Comment by stefanor** [comment]
So, there is a way to specify feature-specific dependencies, but they aren't particularly useful.

**Comment by blaix** [comment]
I did both.

**Comment by stefanor** [comment]
:+1:

**Pull request merged**
